### ISSUE TITLE
redis消息同步问题

### ISSUE THREAD

**Issue by Cranberrycrisp** [pwh-pwh/aiwechat-vercel#11]
如图，Question2被Q3覆盖，且 redis 记录中的Q2、Q3回答不同，看上去是Q2被覆盖前后请求了两次api

![image](https://github.com/pwh-pwh/aiwechat-vercel/assets/53962816/fd8650f7-5adf-4580-ae8a-70a5e045c774)

**Comment by pwh-pwh** [comment]
打算先这样了，解决方案暂时是连续问答间隙长一点，强行同步会让下次回复变慢，更加不利于用户体验

**Comment by pwh-pwh** [comment]
解决掉了，你可以更新一下代码，是本地缓存的问题
