### ISSUE TITLE
feat：能支持个人企业微信部署吗

### ISSUE THREAD

**Issue by chaos-zhu** [pwh-pwh/aiwechat-vercel#13]
rt

**Comment by pwh-pwh** [comment]
企业微信官方支持群机器人，也是webhook方式，可以添加支持

**Comment by chaos-zhu** [comment]
> 企业微信官方支持群机器人，也是webhook方式，可以添加支持

大佬加油

**Comment by pwh-pwh** [comment]
@chaos-zhu 大佬有兴趣也可以单独提个分支pr

**Comment by chaos-zhu** [comment]
> @chaos-zhu 大佬有兴趣也可以单独提个分支pr

不会go，尴尬😅

**Comment by leochen-g** [comment]
对于个人企业微信 hook有兴趣，可以了解这个项目 https://github.com/leochen-g/wechat-assistant-pro
