### ISSUE TITLE
[ BUG ] 乱码问题貌似并未修复成功？

### ISSUE THREAD

**Issue by W4ddl3** [pwh-pwh/aiwechat-vercel#23]
![Shot 2024-03-12 at 10 19 17@2x](https://github.com/pwh-pwh/aiwechat-vercel/assets/141616559/d0853b8e-2dc2-4683-9fac-2b3a338655d3)

Edge、Chrome、Safari、LibreWolf（基于 Firefox）均乱码

**Comment by pwh-pwh** [comment]
你这边看看代码有没有更新到最新，我测试过了，都可以

**Comment by W4ddl3** [comment]
> 你这边看看代码有没有更新到最新，我测试过了，都可以

我是今早才fork的，我测试在微信上聊天都没问题了

**Comment by pwh-pwh** [comment]
你的是mac系统，我不知道是不是和这个有关系，我用的是windows上面测试的，不过不影响使用

**Comment by pwh-pwh** [comment]
我mac系统也测试了，没有乱码问题
