### ISSUE TITLE
【BUG】询问复杂问题时报错504，上下文连贯性问题

### ISSUE THREAD

**Issue by JasonLeeForOnly** [pwh-pwh/aiwechat-vercel#24]
如题
---

### 环境
Bot：gpt-4

### 问题描述
1.在我询问一个复杂问题时，会出现网关超时的问题。
![54aa96217f40eeee8c0e429d578a7f7](https://github.com/pwh-pwh/aiwechat-vercel/assets/47520063/a6158f96-347e-4db0-b24e-c0a6b4b4abc8)
2.上下文连贯性有些问题
![image](https://github.com/pwh-pwh/aiwechat-vercel/assets/47520063/40a34ade-c4d7-4eb5-b4a6-8caf64bb19d7)

### 优化建议
- 等待请求响应时间，是否可以支持自定义？
- 超出500个字符的回答，是否可以分多次回应，避免被微信吞掉。

**Comment by pwh-pwh** [comment]
关于超时问题，vercel的免费版functions限制10s内，这个无法解决，只能升级订阅。关于超出字符问题,现在支持设置system prompt可以在这里做限制，由于微信公众号只能支持一问一答类似webhook的模式，不支持主动发送信息，所以不能自动分多次回应

**Comment by JasonLeeForOnly** [comment]
> 关于超时问题，vercel的免费版functions限制10s内，这个无法解决，只能升级订阅。关于超出字符问题,现在支持设置system prompt可以在这里做限制，由于微信公众号只能支持一问一答类似webhook的模式，不支持主动发送信息，所以不能自动分多次回应

好的，感谢回复！
就是用 /prompt 在客户端层面主动自定义吧~因为你的项目描述还未更新，我以为这个功能还未提供。
是否可以考虑支持在服务端部署的时候就自定义，类似于coze，用户可以自己对bot进行预设。保存后，他会默认加上系统默认的预设，用以限制bot的行为。

**Comment by pwh-pwh** [comment]
这个后面再看看实现方案，后面考虑加入管理员功能，就可以限制用户设置prompt了

**Comment by JasonLeeForOnly** [comment]
> 这个后面再看看实现方案，后面考虑加入管理员功能，就可以限制用户设置prompt了

🆗
谢谢

**Comment by 14790897** [comment]
太容易超时了

**Comment by pwh-pwh** [comment]
cf worker是直接转发了请求，而且好像超时时间很长，vercel免费版的只支持10s的回复时间

**Comment by 14790897** [comment]
cf worker不计算等待时间，只计算cpu时间
