### ISSUE TITLE
必须是服务号才行吗，个人的订阅号是不是不可以

### ISSUE THREAD

**Issue by BDTA-zky** [pwh-pwh/aiwechat-vercel#25]

**Comment by wensley** [comment]
个人订阅号也是可以的

**Comment by BDTA-zky** [comment]
我这边都弄好了但是不能回答

**Comment by BDTA-zky** [comment]
invalid character '<' looking for beginning of value它只会回答这个

**Comment by pwh-pwh** [comment]
> invalid character '<' looking for beginning of value它只会回答这个

你这个是url配置错了，检查一下

**Comment by BDTA-zky** [comment]
谢谢大佬，已经解决了，个人api地址也需要加上/v1
