### ISSUE TITLE
微信公众号无响应

### ISSUE THREAD

**Issue by haozhang86** [pwh-pwh/aiwechat-vercel#26]
你好，我这个是个人订阅号，我搭建好之后。
使用https://域名/api/chat?msg=hi 是有信息输出的：
_你好！有什么我可以帮您的吗？_
使用/api/check 信息如下：
```
echo: true
gpt: true
spark: true
qwen: false
gemini: true
DEFAULT BOT: spark
```

但是在公众号发消息，却无响应，请问是什么情况啊

**Comment by pwh-pwh** [comment]
微信公众平台设置好url和token，开启自动回复功能了吗，检查一下

**Comment by pwh-pwh** [comment]
把botType改成echo 重新部署看看能不能得到复读机的效果

**Comment by haozhang86** [comment]
> 把botType改成echo 重新部署看看能不能得到复读机的效果

改成echo后，用[https://域名/api/chat?msg=hi](https://xn--eqrt2g/api/chat?msg=hi)调用，也无响应，网页直接报错了

**Comment by haozhang86** [comment]
> 把botType改成echo 重新部署看看能不能得到复读机的效果

改成echo后，用[https://域名/api/chat?msg=hi](https://xn--eqrt2g/api/chat?msg=hi)调用，也无响应，网页直接报错了

**Comment by pwh-pwh** [comment]
你把你/wx的完整日志发下看看

**Comment by pwh-pwh** [comment]
我看你日志接收的消息为nil，我怀疑是你WX_TOKEN配置错了

**Comment by haozhang86** [comment]
> 你把你/wx的完整日志发下看看

是这样吗
![image](https://github.com/pwh-pwh/aiwechat-vercel/assets/56377040/f16674bd-b763-4e68-8b45-e4ad099edf16)

woga我刚才又重新部署了一下，用的botType选的是spark，我在公众号请求了很多次，但是只有偶尔会返回消息，估计是返回无响应了，

**Comment by haozhang86** [comment]
那我修改下WX_TOKEN再试一下

**Comment by pwh-pwh** [comment]
换gpt或者gemini吧，可能是spark太慢了，问题复杂的话。能偶尔返回消息就代表配置没有问题

**Comment by haozhang86** [comment]
感谢佬耐心解答，我去试试
