### ISSUE TITLE
启动后，发送消息返回error

### ISSUE THREAD

**Issue by hxrenyan** [pwh-pwh/aiwechat-vercel#28]
error, status code: 403, message: invalid character '<' looking for beginning of value
请求后返回，请问是什么原因

**Comment by pwh-pwh** [comment]
这个是gpt的url配置错了，看看有没有加上/v1

**Comment by hxrenyan** [comment]
加了还是返回这个错误

**Comment by hxrenyan** [comment]
可以了，谢谢
