### ISSUE TITLE
建议环境变量里设置 prompt

### ISSUE THREAD

**Issue by lmm214** [pwh-pwh/aiwechat-vercel#44]
作为一个特定 gpts 使用，另外增加一个参数，不允许 /help 等命令模式。只在环境变量中设置。

**Comment by pwh-pwh** [comment]
命令模式可以通过后期增加管理员功能实现，环境变量设置过于繁琐

**Comment by lmm214** [comment]
嗯，是的，需要管理员模式，避免滥用
