### ISSUE TITLE
vercel部署失败

### ISSUE THREAD

**Issue by warmingkkk** [pwh-pwh/aiwechat-vercel#46]
<img width="1083" alt="微信图片_20240328013702" src="https://github.com/pwh-pwh/aiwechat-vercel/assets/47290788/ed51160d-9a1e-45ff-a129-529bab19fed1">
佬，我重复部署几次都失败了，这是什么问题？

**Comment by pwh-pwh** [comment]
这个错误我这边不好排查，正常来说fork了本项目，导入部署就可以了

**Comment by warmingkkk** [comment]
已解决，在vercel项目setting里面把node的版本调整回18就行
