### ISSUE TITLE
重复响应问题

### ISSUE THREAD

**Issue by QAbot-zh** [pwh-pwh/aiwechat-vercel#47]
查看 newapi 的记录能看到有时候会发起两次请求：

![image](https://github.com/pwh-pwh/aiwechat-vercel/assets/40236765/372c5ab8-e185-45cd-a2e1-36534fe7fe0d)

对应 vercel 的 log 也的确是包含了两条：

![image](https://github.com/pwh-pwh/aiwechat-vercel/assets/40236765/608b7619-2b7a-4806-b348-a8144e987b57)

![image](https://github.com/pwh-pwh/aiwechat-vercel/assets/40236765/0f00134b-02c6-4a92-bad7-d81280271e06)

这是某种重试 bug 吗？

**Comment by pwh-pwh** [comment]
不是，微信公众号本身会重试，5s时间
