### ISSUE TITLE
公众号复读机（个人订阅号）

### ISSUE THREAD

**Issue by spacex-3** [pwh-pwh/aiwechat-vercel#5]
大佬求助，我部署完了后，用你的域名/api/chat?msg=你的问题是可以正常返回答复

但是公众号问问题就跟复读机一样只会回复我问的问题

**Comment by pwh-pwh** [comment]
把botType改成gpt，默认是echo

**Comment by neoshui** [comment]
> 大佬求助，我部署完了后，用你的域名/api/chat?msg=你的问题是可以正常返回答复
> 
> 但是公众号问问题就跟复读机一样只会回复我问的问题
应该是机器人累心配置错误
首先使用你的域名/api/check （显示当前bot的配置信息是否正确）
根据信息查看vercel环境变量配置是否正确

**Comment by spacex-3** [comment]
类型是选择了gpt，而且链接/api/chat?msg=问问题是可以正常回复的

**Comment by spacex-3** [comment]
botType，少打了一个e。破案了
