### ISSUE TITLE
部署成功后，针对简单的问题会直接回答，复杂问题没有回答。

### ISSUE THREAD

**Issue by spacex-3** [pwh-pwh/aiwechat-vercel#6]
如题，我看了我反代chatgpt的日志是有生成回答的，但是不知道是否由于回答内容太多/符号太多比如**？导致微信公众号无法发送？

日志如下：

backend-to-api-other_1  | 2024-03-04 06:15:09,893 [INFO] - 完整消息: 成为一个好人是一个长期的过程，需要不断地努力和自我提升。以下是一些成为好人的建议：
backend-to-api-other_1  | 
backend-to-api-other_1  | 1. **善待他人**：尊重他人、理解他们的感受、给予他们关怀和支持。尽量避免伤害他人的行为，而是选择去帮助和鼓励他们。
backend-to-api-other_1  | 
backend-to-api-other_1  | 2. **诚实正直**：诚实是一个好人的基本品质。坦诚地与他人交往，不说谎、不欺骗。保持诚实和透明可以赢得他人的信任和尊重。
backend-to-api-other_1  | 
backend-to-api-other_1  | 3. **善良慷慨**：善良和慷慨是成为一个好人的重要特征。愿意帮助他人、分享自己的资源和时间，对需要帮助的人伸出援手。
backend-to-api-other_1  | 
backend-to-api-other_1  | 4. **尊重差异**：尊重他人的不同观点、信仰、文化和生活方式。学会包容和接纳不同的人群，避免歧视和偏见。
backend-to-api-other_1  | 
backend-to-api-other_1  | 5. **自我反省**：不断审视自己的行为和态度，认识到自己的不足之处并努力改进。接受他人的批评和建议，用心成长。
backend-to-api-other_1  | 
backend-to-api-other_1  | 6. **宽容谅解**：学会宽容和谅解他人的过错和失误。不要轻易怀恨在心，而是选择原谅和释放内心的怨恨。
backend-to-api-other_1  | 
backend-to-api-other_1  | 7. **尊重环境**：爱护环境，保护自然资源，减少对地球的负面影响。积极参与环保活动，为创建一个更美好的地球贡献自己的力量。
backend-to-api-other_1  | 
backend-to-api-other_1  | 8. **关注社会**：关心社会公益事业，为社会贡献力量。可以通过志愿活动、捐款等方式帮助那些需要帮助的人群。
backend-to-api-other_1  | 
backend-to-api-other_1  | 9. **保持谦逊**：谦逊是成为一个好人的重要品质。不自负、不自大，而是保持谦虚和谦恭的态度与他人相处。
backend-to-api-other_1  | 
backend-to-api-other_1  | 10. **积极学习**：不断学习和成长，提升自己的知识和技能。通过不断学习，可以更好地理解世界、认识自己，从而成为一个更好的人。
backend-to-api-other_1  | 
backend-to-api-other_1  | 成为一个好人是一个渐进的过程，需要不断地付出努力和坚持。重要的是，要真诚地对待他人，用心去关爱和帮助他人，以积极的态度去影响和改变周围的世界。
backend-to-api-other_1  | 2024-03-04 06:15:09,894 [INFO] - 接受到停止信号，停止数据处理线程-外层
backend-to-api-other_1  | 192.168.32.1 - - [04/Mar/2024:06:15:10 +0000] "POST /v1/chat/completions HTTP/1.1" 200 4158 "-" "Go-http-client/1.1"

**Comment by pwh-pwh** [comment]
微信公众号有最大回答字符限制好像是500多，检查一下

**Comment by pwh-pwh** [comment]
后续会增加自定义prompt功能

**Comment by spacex-3** [comment]
感谢！期待prompt+gpt-4

**Comment by pwh-pwh** [comment]
已经支持gpt自定义模型，现在有个问题想调研一下，自定义prompt使用环境变量来配置还是使用指令配置(类似tg一样如发送 /prompt 你扮演一个老师 即可配置)

**Comment by Cranberrycrisp** [comment]
@pwh-pwh 配置了redis后，发送消息，bot回答的都是上一次的提问而不是本次

**Comment by pwh-pwh** [comment]
@Cranberrycrisp 应该不会啊，你可以连接redis看看里面的值，保存了问答记录

**Comment by pwh-pwh** [comment]
@Cranberrycrisp 排查了一下，回答慢的话，同时多个问题会吞了消息，redis没有做加锁控制

**Comment by Cranberrycrisp** [comment]
> @Cranberrycrisp 排查了一下，回答慢的话，同时多个问题会吞了消息，redis没有做加锁控制

连着好几次都是回答的上一个问题，我问的不快，前面有几次api响应错误了，会不会跟这个也有关系？redis中的消息记录只有正常的问答，并没有记录到错误的问题和响应。

**Comment by Cranberrycrisp** [comment]
user

> @Cranberrycrisp 应该不会啊，你可以连接redis看看里面的值，保存了问答记录

![image](https://github.com/pwh-pwh/aiwechat-vercel/assets/53962816/d0492362-385b-463d-874e-18be0b8191a7)

**Comment by pwh-pwh** [comment]
> user
> 
> > @Cranberrycrisp 应该不会啊，你可以连接redis看看里面的值，保存了问答记录
> 
> ![image](https://private-user-images.githubusercontent.com/53962816/310083884-d0492362-385b-463d-874e-18be0b8191a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MzYxNDYsIm5iZiI6MTcwOTYzNTg0NiwicGF0aCI6Ii81Mzk2MjgxNi8zMTAwODM4ODQtZDA0OTIzNjItMzg1Yi00NjNkLTg3NGUtMThiZTBiODE5MWE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDEwNTA0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxYmFiM2RiM2VmOWUzOGQwM2MyMTlkM2VhOWU2NTg1ZTEwMDY1ZjMyZDY5NDhjMzFiYTk4Y2FmOTg5MjdjNDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xhWxk81g1AyBVgxIgvue9RMiOSuO_LEUzCfazP1qa7g)

这里不是没有问题吗

**Comment by Cranberrycrisp** [comment]
> > user
> > > @Cranberrycrisp 应该不会啊，你可以连接redis看看里面的值，保存了问答记录
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/53962816/310083884-d0492362-385b-463d-874e-18be0b8191a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MzYxNDYsIm5iZiI6MTcwOTYzNTg0NiwicGF0aCI6Ii81Mzk2MjgxNi8zMTAwODM4ODQtZDA0OTIzNjItMzg1Yi00NjNkLTg3NGUtMThiZTBiODE5MWE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDEwNTA0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxYmFiM2RiM2VmOWUzOGQwM2MyMTlkM2VhOWU2NTg1ZTEwMDY1ZjMyZDY5NDhjMzFiYTk4Y2FmOTg5MjdjNDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xhWxk81g1AyBVgxIgvue9RMiOSuO_LEUzCfazP1qa7g)
> 
> 这里不是没有问题吗

user第二句被修改了，你可以对照看一下

**Comment by pwh-pwh** [comment]
> > > user
> > > > @Cranberrycrisp 应该不会啊，你可以连接redis看看里面的值，保存了问答记录
> > > 
> > > 
> > > ![image](https://private-user-images.githubusercontent.com/53962816/310083884-d0492362-385b-463d-874e-18be0b8191a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MzYxNDYsIm5iZiI6MTcwOTYzNTg0NiwicGF0aCI6Ii81Mzk2MjgxNi8zMTAwODM4ODQtZDA0OTIzNjItMzg1Yi00NjNkLTg3NGUtMThiZTBiODE5MWE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDEwNTA0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxYmFiM2RiM2VmOWUzOGQwM2MyMTlkM2VhOWU2NTg1ZTEwMDY1ZjMyZDY5NDhjMzFiYTk4Y2FmOTg5MjdjNDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xhWxk81g1AyBVgxIgvue9RMiOSuO_LEUzCfazP1qa7g)
> > 
> > 
> > 这里不是没有问题吗
> 
> user第二句被修改了，你可以对照看一下，redis 第二段 qa 和记录里的都不一样

这个我知道,存消息到redis是异步方式进行的，上一个还没保存就被下一个覆盖了，你提个消息同步的issue，我后面看看有没有什么方案解决

**Comment by pwh-pwh** [comment]
只能加个用于同步的锁解决

**Comment by spacex-3** [comment]
> 已经支持gpt自定义模型，现在有个问题想调研一下，自定义prompt使用环境变量来配置还是使用指令配置(类似tg一样如发送 /prompt 你扮演一个老师 即可配置)

我尝试使用model：gpt-4，貌似没生效，已经是增加环境变量且redeploy了。

另外建议使用环境变量来配置prompt，降低公众使用难度

**Comment by pwh-pwh** [comment]
@spacex-3 你fork的仓库没有同步到最新代码，更新一下就支持了

**Comment by spacex-3** [comment]
> @spacex-3 你fork的仓库没有同步到最新代码，更新一下就支持了

收到！已sync并更新，正常使用4了！感谢
