### ISSUE TITLE
不太确定是否部署成功

### ISSUE THREAD

**Issue by imrayyu** [pwh-pwh/aiwechat-vercel#76]
感谢大佬的项目！

在部署完成后，访问/api/check后，显示如下内容：
echo: true
gpt: true
spark: false
qwen: false
gemini: false
DEFAULT BOT: gpt

没有显示“check ok”的提示。

订阅号是可以进行回复的，但是发送/getmodel指令后，回复“gpt 当前未设置model”，所以想问一下这种情况是部署成功了还是失败了呢？

**Comment by imrayyu** [comment]
同时在环境变量中把模型切换为gpt-4o-mini后，貌似订阅号依然是使用的默认gpt3.5 turbo模型，所以不知道是否算是成功。。

**Comment by pwh-pwh** [comment]
部署成功了

**Comment by imrayyu** [comment]
> 部署成功了

感谢大佬
